version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ms-email
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cHJvbWV0aGV1cw==}
    ports:
      - "5432:5432"
